[recipe]
interpreter = "sh"

[[step]]
run = """
URL="https://raw.githubusercontent.com/HuntedByTheIRS/curlopsec/main/opsec.sh"
TARGET="/usr/local/bin/opsec"

curl -sL "$URL" -o /tmp/opsec.sh
sudo install -m 755 /tmp/opsec.sh "$TARGET"

rm /tmp/opsec.sh
"""
